export const USER_LOGIN = "LOGIN/LOGIN";
export const USER_LOGIN_FAIL = "LOGIN/LOGIN_FAIL";
export const DELETE_USER_SESSION = "LOGIN/DELETE_USER_SESSION";

export const SHOW_MODAL = "LOGIN/SHOW_MODAL";
export const HIDE_MODAL = "LOGIN/HIDE_MODAL";
