json.locale "en"
json.HOME "Home"
json.CHAR_SEARCH_DESCR "Character Search"
json.CHAR_SEARCH_OPTION "Options"
json.CHAR_SEARCH_RESULT "Results"
json.LOGIN "Login"
json.LOGOUT "Logout"
json.SIGNUP "Sign Up"
json.MY_LIST "My List"
json.CHAR_CREATION_DESCR "Character Creation"
json.LANGUAGE "Language"
json.SIGNUP_LOGIN "Signup / Login"
json.JAPANESE "日本語"
json.ENGLISH "English"
